name: MPICH

on:
  push:
    branches:
      - master
      - github_action
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.jpg'
      - '**.png'
  pull_request:
    branches: master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.jpg'
      - '**.png'

jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - uses: actions/checkout@v2
        - name: Set up dependencies
          run: |
            sudo apt-get update
            sudo apt-get install automake autoconf libtool libtool-bin m4 cmake
            cmake --version
            # mpich
            sudo apt-get install mpich
            # zlib
            sudo apt-get install zlib1g-dev
        - name: Install ADIOS2
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}
            echo "Install ADIOS2 on ${GITHUB_WORKSPACE}/ADIOS"
            rm -rf ADIOS
            mkdir ADIOS
            cd ADIOS
            VERSION=2.8.3
            wget -cq https://github.com/ornladios/ADIOS2/archive/refs/tags/v${VERSION}.tar.gz
        - name: untar
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}/ADIOS
            VERSION=2.8.3
            tar -zxf v${VERSION}.tar.gz
            mkdir adios2_build
        - name: cmake
          if: ${{ success() }}
          run: |
            VERSION=2.8.3
            cd ${GITHUB_WORKSPACE}/ADIOS/adios2_build
            CC=mpicc \
            CXX=mpicxx \
            cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/ADIOS \
                  -DADIOS2_USE_MPI=ON \
                  ../ADIOS2-${VERSION}
        - name: make
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}/ADIOS/adios2_build
            make
        - name: make install
          if: ${{ success() }}
          run: |
            cd ${GITHUB_WORKSPACE}/ADIOS/adios2_build
            make install
            make clean
        - name: dump
          if: ${{ failure() }}
          run: |
            cd ${GITHUB_WORKSPACE}/ADIOS/adios2_build
            echo "---- ../lib/cmake/adios2/adios2-config.cmake ------------------------------------------------------------"
            cat ../lib/cmake/adios2/adios2-config.cmake
            echo "---- cmake/install/post/cmake_install.cmake ------------------------------------------------------------"
            cat cmake/install/post/cmake_install.cmake
            echo "---- cmake/install/post/generate-adios2-config.sh ------------------------------------------------------------"
            cat cmake/install/post/generate-adios2-config.sh
            echo "----- CMakeFiles/CMakeOutput.log -----------------------------------------------------------"
            cat CMakeFiles/CMakeOutput.log
 
